routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages/welcome');
});

Auth::routes();

Route::get('/home',[App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('event', \App\Http\Controllers\EventController::class)->middleware(['auth','checkRole:2']);
Route::resource('/event/posts', EventController::class)->middleware(['auth','checkRole:2']);

Route::resource('user', \App\Http\Controllers\UserController::class)->middleware(['auth','checkRole:2']);


Route::resource('events', \App\Http\Controllers\EventUserController::class)->middleware(['auth','checkRole:1']);
Route::resource('/events/posts', \App\Http\Controllers\EventUserController::class)->middleware(['auth','checkRole:1']);

Route::resource('profil', \App\Http\Controllers\ProfilController::class)->middleware(['auth','checkRole:1']);

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use HasFactory;

    protected $fillable = [
        'foto',
        'nama',
        'dt',
        'deskripsi',
    ];

    public function userevent(){
        return $this->hasMany(UserEvent::class, 'event_id');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use Illuminate\Http\Request;
use Illuminate\Support\Facedes\Gate;
use Illuminate\Support\Facades\Storage;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $event = Event::all();

        return view('pages/admin/event/event', [
            'event' => $event
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages/admin/event/event_create',[
            "title" => "Tambah Data Event",
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'nama'=>'required|min:5',
            'foto'=>'required|image|file|mimes:jpg,png,jpeg|max:2084',
            'dt'  =>'required',
            'deskripsi'=>'required',
        ],[
            'nama.required' => 'Nama event harus diisi',
            'foto.required' => 'Foto harus dipilih',
            'dt.required'   => 'Tanggal harus diisi',
            'deskripsi.required' => 'Deskripsi harus diisi',
            'nama.min'      => 'Nama event harus lebih dari 5 karakter',
            'foto.image'    => 'Foto harus berupa gambar',
            'foto.mimes'    => 'Foto harus berupa jpg/png/jpeg'
        ]);

        $validatedData['foto'] = $request->file('foto')->store('foto');

        Event::create($validatedData);

        return redirect()->route('event.index')->with('success_message', 'Berhasil menambah event baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('pages/admin/event/event_detail',[
            'data' => Event::find($id)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Event::find($id);
        if (!$event) return redirect()->route('event.index')
            ->with('error_message', 'Event dengan id'.$id.' tidak ditemukan');
        return view('pages/admin/event/event_update', [
            'event' => $event
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
        $request->validate([
            'nama' => 'required',
            'foto'=>'required|image|file|mimes:jpg,png,jpeg|max:2084',
            'dt'  =>'required',
            'deskripsi'=>'required',
        ],[
            'nama.required' => 'Nama event harus diisi',
            'foto.required' => 'Foto harus dipilih',
            'dt.required'   => 'Tanggal harus diisi',
            'deskripsi.required' => 'Deskripsi harus diisi',
            'nama.min'      => 'Nama event harus lebih dari 5 karakter',
            'foto.image'    => 'Foto harus berupa gambar',
            'foto.mimes'    => 'Foto harus berupa jpg/png/jpeg'
        ]);

        $event = Event::find($id);
        $event->nama = $request->nama;
        $event->dt = $request->dt;
        $event->deskripsi = $request->deskripsi;
        
        if($request->file('foto')){ 
            if($request->oldFoto){
                Storage::delete($request->oldFoto);
            }
            $event->foto = $request->file('foto')->store('foto');
        }
        
        $event->save();
        return redirect()->route('event.index')
            ->with('success_message', 'Berhasil mengubah data event');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $event = Event::find($id);
        
        if($event->foto){
            Storage::delete($event->foto);
        }
        
        if ($event) $event->delete();
        return redirect()->route('event.index')
            ->with('success_message', 'Berhasil menghapus event');
    }
}

resources/views/pages/admin/event/event.blade.php
@extends('adminlte::page')

@section('title', 'Data Event')

@section('content_header')
    
@stop

@section('content')
<br>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3" style="display: flex; justify-content: space-between;">
                      <h1 class="text-dark">Data Event</h1>
                      <a href="{{route('event.create')}}" class="btn btn-primary mb-3">
                        Tambah
                      </a>
                    </div>
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Opsi</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($event as $key => $event)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$event->nama}}</td>
                                <td>
                                    <a href="{{route('event.show', $event)}}" class="btn btn-success btn-xs">
                                        Detail
                                    </a>
                                    <a href="{{route('event.edit', $event)}}" class="btn btn-primary btn-xs">
                                        Edit
                                    </a>
                                    <a href="{{route('event.destroy', $event)}}" onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-xs">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    <form action="" id="delete-form" method="post">
        @method('delete')
        @csrf
    </form>
    <script>
        $('#example2').DataTable({
            "responsive": true,
        });

        function notificationBeforeDelete(event, el) {
            event.preventDefault();
            if (confirm('Apakah anda yakin akan menghapus data ? ')) {
                $("#delete-form").attr('action', $(el).attr('href'));
                $("#delete-form").submit();
            }
        }

    </script>
@endpush

resources/views/pages/admin/event/event_create.blade.php
@extends('adminlte::page')

@section('title', 'Laravel Event')

@section('content_header')
    <h1 class="m-0 text-dark">Data Event</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h1>
                      Tambah Data Event
                    </h1>
                    <div>
                        <form class="row g-3" action="/event/posts" method="post" enctype="multipart/form-data">
                            @csrf
                          <div class="col-md-12">
                            <label for="nama" class="form-label">Nama Event</label>
                            <input type="text" class="form-control @error ('nama') is-invalid @enderror" id="nama" name="nama" value="{{ old('nama') }}">
                            @error('nama')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                          <div class="col-md-12">
                            <label for="foto" class="form-label">Gambar</label>
                            <img class="img-preview img-fluid mb-3 col-sm-3">
                            <input type="file" class="form-control @error ('foto') is-invalid @enderror" id="foto" name="foto" onchange="previewImage()">
                            @error('foto')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                          <div class="col-md-12">
                            <label for="dt" class="form-label">Tanggal</label>
                            <input type="datetime-local" class="form-control @error ('dt') is-invalid @enderror" id="dt" name="dt" value="{{ old('dt') }}">
                            @error('dt')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                          <div class="col-md-12">
                            <label for="deskripsi" class="form-label">Deskripsi</label>
                            <textarea class="form-control @error ('deskripsi') is-invalid @enderror" id="deskripsi" name="deskripsi" value="{{ old('deskripsi') }}"></textarea>
                            @error('deskripsi')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                          <div class="col-md-12 mt-2">
                            <button type="submit" class="btn btn-primary">Tambah</button>
                          </div>
                        </form>
                      
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
      function previewImage(){
        const foto = document.querySelector('#foto');
        const imgPreview = document.querySelector('.img-preview');

        imgPrewiew.style.display = 'block';

        conts oFReader = new FileReader();
        oFReader.readAsDataURL(foto.files[0]);

        oFReader.onload = function(oFREvent){
          imgPreview.src = oFREvent.target.result;
        }
      }
    </script>
@stop

resources/views/pages/admin/event/event_detail.blade.php
@extends('adminlte::page')

@section('title', 'Detail Event')

@section('content_header')
@stop

@section('content')
<br>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3" style="display: flex; justify-content: space-between;">
                      <h1 class="text-dark">Detail Event</h1>
                      <a href="/event" class="btn btn-secondary mb-3">
                        Kembali
                      </a>
                    </div>
                    

                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <td colspan="2" align="center"></td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>Nama Event</th>
                                <td>{{$data->nama}}</td>
                            </tr>
                            <tr>
                                <th>Tanggal Pelaksanaan</th>
                                <td>{{$data->dt}}</td>
                            </tr>
                            <tr> 
                                <th>Foto</th>
                                <td>
                                    <img src="{{asset('storage/'.$data->foto)}}" class="mb-3 col-sm-3">
                                </td>
                            </tr>
                            <tr>
                                <th>Deskripsi</th>
                                <td>{{$data->deskripsi}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/pages/admin/event/event_update.blade.php
@extends('adminlte::page')

@section('title', 'Laravel Event')

@section('content_header')
    <h1 class="m-0 text-dark">Data Event</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h1>
                      Ubah Data Event
                    </h1>
                    <div>
                        <form class="row g-3" action="{{route('event.update', $event)}}" method="post" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                          <div class="col-md-12">
                            <label for="nama" class="form-label">Nama Event</label>
                            <input type="text" class="form-control @error ('nama') is-invalid @enderror" id="nama" name="nama" value="{{$event->nama ?? old('nama')}}">
                            @error('nama')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                          <div class="col-md-12">
                            <label for="foto" class="form-label">Gambar</label>
                            @if($event->foto)
                              <img class="img-preview img-fluid mb-3 col-sm-3 d-block" src="{{ asset('storage/' . $event->foto) }}">
                            @else
                              <img class="img-preview img-fluid mb-3 col-sm-3 d-block">
                            @endif
                            <input type="hidden" name="oldFoto" value="{{ $event->foto }}">
                            <input type="file" class="form-control @error ('foto') is-invalid @enderror" id="foto" name="foto" onchange="previewImage()">
                            @error('foto')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                          <div class="col-md-12">
                            <label for="dt" class="form-label">Tanggal</label>
                            <input type="datetime-local" class="form-control @error ('dt') is-invalid @enderror" id="dt" name="dt" value="{{ $event->dt ?? old('dt') }}">
                            @error('dt')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                          <div class="col-md-12">
                            <label for="deskripsi" class="form-label">Deskripsi</label>
                            <textarea class="form-control @error ('deskripsi') is-invalid @enderror" id="deskripsi" name="deskripsi">{{ $event->deskripsi ?? old('deskripsi') }}</textarea>
                            @error('deskripsi')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                          </div>
                          <div class="col-md-12 mt-2">
                            <button type="submit" class="btn btn-primary">Ubah</button>
                          </div>
                        </form>
                      
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
      function previewImage(){
        const foto = document.querySelector('#foto');
        const imgPreview = document.querySelector('.img-preview');

        imgPrewiew.style.display = 'block';

        conts oFReader = new FileReader();
        oFReader.readAsDataURL(foto.files[0]);

        oFReader.onload = function(oFREvent){
          imgPreview.src = oFREvent.target.result;
        }
      }
    </script>
@stop